export {default as Home} from './Home'
export {default as Group} from './Group'
export {default as News} from './News'
export {default as NewsDetails} from './NewsDetails'
export {default as Registration} from './RegistrationInfo'
export {default as Contacts} from './Contacts'
export {default as ParentsInfo} from './ParentsInfo'
