export {default as Header} from './Header'
export {default as Footer} from './Footer'
export {default as Nav} from './Navigation'
export {default as Aside} from './Aside'
export {default as NewsCard} from './NewsCard'
export {default as MyGoogleMap} from './GoogleMap'
export {default as Spinner} from './Spinner'